project:
  type: website

website:
  title: "haileycsy"
  image: "images/Name_Logo2.png"
  favicon: "images/apple-touch-icon.png"
  page-navigation: true
  navbar:
    logo: "images/Name_Logo2.png"
    title: false
    collapse-below: lg
    search: true
    
    left:
      - icon: linkedin
        href: https://www.linkedin.com/in/hailey-sy-cheong/
        aria-label: Linkedin
      - icon: diagram-3-fill
        href: https://public.tableau.com/app/profile/hailey.cheong
        aria-label: Tableau
      - icon: github
        href: https://github.com/haileycsy
        aria-label: Github
        
    right:
      - text: "{{< fa face-smile >}} Hello World"
        href: about.html

      - text: "{{< fa hand-sparkles >}} Hands-on Ex"
        menu:
          - text: "Hands-on Ex 1"
            href: Hands-on_Ex/hoe1/Hands-on_Ex01.html
          - text: "Hands-on Ex 2"
            href: Hands-on_Ex/hoe2/Hands-on_Ex02.html
     
      - text: "{{< fa magnifying-glass-chart >}} Take-home Ex"
        menu:
          - text: "Take-home Ex 1"
          - text: "Take-home Ex 2"
          
      - text: "{{< fa chalkboard-user >}} In-class Ex"
        menu:
          - text: "In-class Ex 1"
            href: In-class_Ex\ice1\In-class_Ex01.html
          - text: "In-class Ex 2"
            href: In-class_Ex\ice2\In-class_Ex02.html
    
  page-footer:
    right: |
      Copyright 2023![](images/Name_Logo3.png){fig-alt="Name_logo" width=100px}
format:
  html:
    toc: true
    theme: 
      - cosmo
      - theme.scss
    highlight-style: tango
    code-copy: hover
    code-overflow: wrap
    css: styles.css
    

editor: visual

